import { useEffect, useState } from "react";
import { api } from "./api";

const emptySubject = { name: "", description: "", color: "#1f6b50", progress: 0 };
const emptyTask = { title: "", description: "", due_date: "", priority: "Medium", subject: "" };
const emptyNote = { title: "", content: "", subject: "" };
const navigation = [["dashboard", "Overview"], ["subjects", "Subjects"], ["tasks", "Tasks"], ["notes", "Notes"], ["sessions", "Study timer"], ["progress", "Progress"]];

function Stat({ label, value, detail, tone = "sage" }) { return <article className={`stat-card ${tone}`}><span className="stat-detail">{detail}</span><p>{label}</p><strong>{value}</strong></article>; }

function Workspace({ user, onLogout }) {
  const [page, setPage] = useState("dashboard");
  const [data, setData] = useState({ subjects: [], tasks: [], notes: [], sessions: [], dashboard: {}, progress: {} });
  const [busy, setBusy] = useState(true); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  async function load() { setBusy(true); setError(""); try { const [subjects, tasks, notes, sessions, dashboard, progress] = await Promise.all([api("/subjects/"), api("/tasks/"), api("/notes/"), api("/sessions/"), api("/dashboard/"), api("/progress/")]); setData({ subjects: subjects || [], tasks: tasks || [], notes: notes || [], sessions: sessions || [], dashboard: dashboard || {}, progress: progress || {} }); } catch (requestError) { setError(requestError.message); } finally { setBusy(false); } }
  useEffect(() => { load(); }, []);
  async function save(path, payload, method = "POST") { setError(""); try { await api(path, { method, body: JSON.stringify(payload) }); setNotice("Saved successfully."); await load(); } catch (requestError) { setError(requestError.message); } }
  async function remove(path) { if (!window.confirm("Delete this item permanently?")) return; try { await api(path, { method: "DELETE" }); setNotice("Item deleted."); await load(); } catch (requestError) { setError(requestError.message); } }
  const activeTasks = data.tasks.filter((task) => !task.completed).length; const initials = user.username.slice(0, 1).toUpperCase(); const title = navigation.find(([key]) => key === page)?.[1] || "Overview";
  return <div className="dashboard-shell"><aside className="sidebar"><div className="logo"><span className="logo-mark">SS</span><span className="logo-copy"><strong>Smart Study</strong><small>Room</small></span></div><nav aria-label="Primary navigation">{navigation.map(([key, label]) => <button key={key} className={page === key ? "active" : ""} onClick={() => { setPage(key); setNotice(""); }}><span className={`nav-icon nav-${key}`} />{label}</button>)}</nav><div className="sidebar-footer"><div className="mini-profile"><span className="avatar">{initials}</span><span><strong>{user.username}</strong><small>Student</small></span></div><button className="logout" onClick={onLogout}><span className="logout-icon">↪</span>Log out</button></div></aside><main className="main"><header className="topbar"><div><p className="eyebrow">{page === "dashboard" ? "TUESDAY, SEPTEMBER 8" : "YOUR WORKSPACE"}</p><h1>{page === "dashboard" ? `Good morning, ${user.username}.` : title}</h1><p className="subtitle">{page === "dashboard" ? "A clear mind makes room for meaningful progress." : "Keep your learning rhythm moving forward."}</p></div><div className="profile"><span className="avatar">{initials}</span><span><strong>{user.username}</strong><small>Student account</small></span></div></header>{error && <div className="alert error" role="alert">{error}</div>}{notice && <div className="alert success" role="status">{notice}</div>}{busy ? <div className="loading"><span className="spinner" />Loading your workspace...</div> : <PageContent page={page} data={data} activeTasks={activeTasks} save={save} remove={remove} setPage={setPage} />}</main></div>;
}

function PageContent({ page, data, activeTasks, save, remove, setPage }) {
  const dashboard = data.dashboard || {};
  if (page === "dashboard") return <><section className="hero-banner"><div><p className="eyebrow">TODAY'S FOCUS</p><h2>Make today count.</h2><p>Small, focused sessions add up. You have {activeTasks} active {activeTasks === 1 ? "task" : "tasks"} waiting.</p></div><button className="primary-btn" onClick={() => setPage("sessions")}>Start a session <span>→</span></button></section><section className="stats"><Stat label="Subjects" value={dashboard.subjects || 0} detail="In your library" /><Stat label="Active tasks" value={dashboard.pending_tasks || 0} detail="Still to do" tone="peach" /><Stat label="Notes" value={dashboard.notes || 0} detail="Ideas captured" tone="blue" /><Stat label="Study hours" value={`${dashboard.study_hours || 0}h`} detail="All time" tone="gold" /></section><section className="dashboard-grid"><Panel title="Today's tasks" subtitle="Your next small wins" action="View tasks" onAction={() => setPage("tasks")}><TaskList tasks={dashboard.today_tasks || []} /></Panel><Panel title="My subjects" subtitle="Your learning areas" action="Manage" onAction={() => setPage("subjects")}><SubjectList subjects={data.subjects.slice(0, 4)} /></Panel></section><section className="dashboard-grid lower-grid"><Panel title="Weekly rhythm" subtitle="Minutes focused over the last 7 days"><WeeklyBars days={dashboard.weekly_progress || []} /></Panel><Panel title="Recent sessions" subtitle="Your latest focused work"><SessionList sessions={dashboard.recent_sessions || []} subjects={data.subjects} /></Panel></section></>;
  if (page === "subjects") return <CrudPage title="Subjects" description="Give every area of your learning a home." items={data.subjects} fields={emptySubject} save={save} remove={remove} endpoint="subjects" renderItem={(item) => <><strong>{item.name}</strong><p>{item.description || "No description yet"}</p><div className="inline-progress"><span style={{ width: `${item.progress}%`, background: item.color }} /><small>{item.progress}% complete</small></div></>} />;
  if (page === "tasks") return <CrudPage title="Tasks" description="Turn intentions into a list you can finish." items={data.tasks} fields={emptyTask} save={save} remove={remove} endpoint="tasks" subjects={data.subjects} renderItem={(item) => <><label className="task-toggle"><input type="checkbox" checked={item.completed} onChange={() => save(`/tasks/${item.id}/`, { completed: !item.completed }, "PATCH")} /><strong className={item.completed ? "strike" : ""}>{item.title}</strong></label><p>{item.priority} priority · {item.due_date || "No due date"} {item.subject_name ? `· ${item.subject_name}` : ""}</p></>} />;
  if (page === "notes") return <CrudPage title="Notes" description="Keep the useful details close at hand." items={data.notes} fields={emptyNote} save={save} remove={remove} endpoint="notes" subjects={data.subjects} renderItem={(item) => <><strong>{item.title}</strong><p>{item.content.slice(0, 120)}{item.content.length > 120 ? "..." : ""}</p></>} />;
  if (page === "sessions") return <SessionPage sessions={data.sessions} subjects={data.subjects} save={save} />;
  return <Progress data={data.progress} dashboard={dashboard} />;
}

function Panel({ title, subtitle, action, onAction, children }) { return <section className="card"><div className="card-header"><div><h2>{title}</h2><p>{subtitle}</p></div>{action && <button className="text-btn" onClick={onAction}>{action} <span>→</span></button>}</div>{children}</section>; }
function SubjectList({ subjects }) { return <div className="subject-list">{subjects.length ? subjects.map((item) => <div className="subject-row" key={item.id}><span className="subject-dot" style={{ background: item.color }} /><div><strong>{item.name}</strong><p>{item.description || "Ready for your next session"}</p></div><b>{item.progress}%</b></div>) : <p className="empty">No subjects yet. Add your first one to begin.</p>}</div>; }
function TaskList({ tasks }) { return <div className="task-list">{tasks.length ? tasks.map((item) => <div className="task-row" key={item.id}><span className={`check ${item.completed ? "checked" : ""}`}>{item.completed ? "✓" : ""}</span><div><strong className={item.completed ? "strike" : ""}>{item.title}</strong><p>{item.priority} priority {item.subject_name ? `· ${item.subject_name}` : ""}</p></div></div>) : <p className="empty">Nothing due today. A little breathing room.</p>}</div>; }
function SessionList({ sessions, subjects }) { return <div className="session-list">{sessions.length ? sessions.map((item) => <div className="session-row" key={item.id}><span className="session-glyph">◷</span><div><strong>{item.duration} minutes</strong><p>{subjects.find((subject) => subject.id === item.subject)?.name || "General study"}</p></div><small>{new Date(item.session_date).toLocaleDateString(undefined, { month: "short", day: "numeric" })}</small></div>) : <p className="empty">Your completed sessions will appear here.</p>}</div>; }
function WeeklyBars({ days }) { const max = Math.max(...days.map((day) => day.minutes), 1); return <div className="week-bars">{days.map((day) => <div className="bar-column" key={day.date}><div className="bar-wrap"><div className="bar" style={{ height: `${Math.max((day.minutes / max) * 120, day.minutes ? 12 : 5)}px` }} /></div><small>{new Date(`${day.date}T12:00:00`).toLocaleDateString(undefined, { weekday: "short" }).slice(0, 2)}</small></div>)}</div>; }

function CrudPage({ title, description, items, fields, save, remove, endpoint, subjects = [], renderItem }) {
  const [form, setForm] = useState({ ...fields }); const [editing, setEditing] = useState(null); const [open, setOpen] = useState(false);
  function update(event) { setForm({ ...form, [event.target.name]: event.target.value }); }
  function submit(event) { event.preventDefault(); const payload = { ...form, ...(form.progress !== undefined ? { progress: Number(form.progress) } : {}), ...(form.subject ? { subject: Number(form.subject) } : { subject: null }), ...(form.due_date !== undefined ? { due_date: form.due_date || null } : {}) }; save(editing ? `/${endpoint}/${editing}/` : `/${endpoint}/`, payload, editing ? "PUT" : "POST"); setForm({ ...fields }); setEditing(null); setOpen(false); }
  function edit(item) { setEditing(item.id); setForm(Object.fromEntries(Object.keys(fields).map((key) => [key, item[key] ?? ""]))); setOpen(true); }
  return <><section className="page-intro"><div><p className="eyebrow">YOUR LIBRARY</p><h2>{title}</h2><p>{description}</p></div><button className="primary-btn" onClick={() => { setForm({ ...fields }); setEditing(null); setOpen(!open); }}>{open ? "Close" : `Add ${title.slice(0, -1)}`} <span>{open ? "×" : "+"}</span></button></section>{open && <form className="card resource-form" onSubmit={submit}>{Object.entries(fields).map(([key]) => key === "subject" ? <label key={key}>Subject<select name={key} value={form[key]} onChange={update}><option value="">No subject</option>{subjects.map((subject) => <option value={subject.id} key={subject.id}>{subject.name}</option>)}</select></label> : key === "description" || key === "content" ? <label key={key}>{key === "content" ? "Content" : "Description"}<textarea name={key} value={form[key]} onChange={update} required={key === "content"} /></label> : key === "priority" ? <label key={key}>Priority<select name={key} value={form[key]} onChange={update}>{["Low", "Medium", "High"].map((priority) => <option key={priority}>{priority}</option>)}</select></label> : <label key={key}>{key.replace("_", " ")}<input type={key === "progress" ? "number" : key === "due_date" ? "date" : key === "color" ? "color" : "text"} min={key === "progress" ? 0 : undefined} max={key === "progress" ? 100 : undefined} name={key} value={form[key]} onChange={update} required={key === "name" || key === "title"} /></label>)}<button className="button primary" type="submit">{editing ? "Update" : "Create"} {title.slice(0, -1).toLowerCase()}</button></form>}<div className="resource-list">{items.map((item) => <article className="resource-row" key={item.id}><div className="resource-copy">{renderItem(item)}</div><div className="row-actions"><button className="button" onClick={() => edit(item)}>Edit</button><button className="button danger" onClick={() => remove(`/${endpoint}/${item.id}/`)}>Delete</button></div></article>)}</div>{!items.length && <p className="empty page-empty">Nothing here yet. Add your first item to get started.</p>}</>;
}

function SessionPage({ sessions, subjects, save }) { const [duration, setDuration] = useState(25); const [subject, setSubject] = useState(""); const [elapsed, setElapsed] = useState(0); const [running, setRunning] = useState(false); useEffect(() => { if (!running) return undefined; const timer = window.setInterval(() => setElapsed((value) => value + 1), 1000); return () => window.clearInterval(timer); }, [running]); const time = `${String(Math.floor(elapsed / 60)).padStart(2, "0")}:${String(elapsed % 60).padStart(2, "0")}`; function finish() { if (elapsed < 60) return; save("/sessions/", { duration: Math.max(1, Math.round(elapsed / 60)), subject: subject ? Number(subject) : null }); setRunning(false); setElapsed(0); } return <><section className="page-intro"><div><p className="eyebrow">FOCUSED TIME</p><h2>Study timer</h2><p>Protect a little time for the work that matters.</p></div></section><section className="timer-layout"><div className="timer-card"><div className="timer-orbit"><span>{time}</span></div><p className="timer-label">{running ? "Deep work in progress" : elapsed ? "Paused when you are ready" : "Ready when you are"}</p><div className="timer-controls"><button className="button primary" onClick={() => setRunning(!running)}>{running ? "Pause" : elapsed ? "Resume" : "Start timer"}</button><button className="button" onClick={() => { setRunning(false); setElapsed(0); }}>Reset</button><button className="button" disabled={elapsed < 60} onClick={finish}>Save session</button></div></div><div className="card timer-settings"><h2>Session details</h2><p>Choose a subject so your progress tells a richer story.</p><label>Subject<select value={subject} onChange={(event) => setSubject(event.target.value)}><option value="">General study</option>{subjects.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Quick duration<input type="number" min="1" value={duration} onChange={(event) => setDuration(event.target.value)} /></label><button className="text-btn" onClick={() => { setElapsed(Number(duration) * 60); setRunning(false); }}>Set timer to {duration} min →</button></div></section><Panel title="Recent sessions" subtitle="Your saved focused time"><SessionList sessions={sessions} subjects={subjects} /></Panel></>; }

function Progress({ data = {}, dashboard = {} }) { return <><section className="page-intro"><div><p className="eyebrow">YOUR RHYTHM</p><h2>Progress</h2><p>Notice the consistency. It is doing the heavy lifting.</p></div></section><section className="stats"><Stat label="Study hours" value={`${data.study_hours || 0}h`} detail="Total focused time" /><Stat label="Completed tasks" value={data.completed_tasks || 0} detail="Finished with intention" tone="peach" /><Stat label="This week" value={`${Math.round((dashboard.weekly_minutes || 0) / 60 * 10) / 10}h`} detail="Last 7 days" tone="gold" /></section><div className="card"><div className="card-header"><div><h2>Weekly study time</h2><p>Minutes studied across the last seven days</p></div></div><WeeklyBars days={dashboard.weekly_progress || []} /></div><div className="card subject-progress"><div className="card-header"><div><h2>Subject activity</h2><p>Progress and time by learning area</p></div></div>{(data.subjects || []).length ? data.subjects.map((subject) => <div className="progress-line" key={subject.id}><div><strong>{subject.name}</strong><span>{subject.minutes} min</span></div><div className="progress-track"><span style={{ width: `${subject.progress}%`, background: subject.color }} /></div><b>{subject.progress}%</b></div>) : <p className="empty">Study sessions by subject will appear here.</p>}</div></>; }

export default Workspace;