# Generated by Django 6.1 on 2026-09-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
